[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./addresses"}]
evm_version = "cancun"

[fmt]
sort_imports = true

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
base = { endpoint= "${BASE_RPC_URL}", retries = 3, retry_backoff = 1000 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url= "https://api.basescan.org/api" }